org: yuanhao
app: ar-camera-backend
service: ar-camera-backend

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  environment:
    SNAPSHOT_TABLE: { "Ref": "SnapshotsDynamoDbTable" } #SNAPSHOT_TABLE is a logicalID also used when provisioning below 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - { "Fn::GetAtt": ["SnapshotsDynamoDbTable", "Arn"] } #you will also see the logical IDs below where they are provisioned for creating DynamoDb tables

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect # authorizers are only for connect routes
          authorizer:
            name: auth
            identitySource:
              - 'route.request.header.Auth'
  disconnect: 
    handler: handler.disconnect
    events:
      - websocket:
        route: $disconnect
  default:
    handler: handler.default
    events:
      - websocket:
          route: $default

  auth:
    handler: handler.auth

resources:
  Resources:
    SnapshotsDynamoDbTable: #this is where the logicalID is defined for DynamoDbTable
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1